# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: koke_kokko.proto
"""Generated protocol buffer code."""
import record_metadata_options_pb2 as record__metadata__options__pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10koke_kokko.proto\x12\x04\x63sdi\x1a\x1drecord_metadata_options.proto\"\xac\x01\n\x04User\x12\x14\n\x05\x65mail\x18\x01 \x01(\tB\x05\x8aM\x02\x08\x01\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x15\n\rprofile_photo\x18\x04 \x01(\t\x12\x16\n\x0e\x66ollow_tag_arr\x18\x05 \x03(\t\x12\x1d\n\x15published_article_arr\x18\x06 \x03(\t\x12\x1c\n\x14\x62ookmark_article_arr\x18\x07 \x03(\t\"\xbd\x01\n\x07\x41rticle\x12\x19\n\narticle_id\x18\x01 \x01(\tB\x05\x8aM\x02\x08\x01\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x12\n\nuser_photo\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x15\n\rarticle_photo\x18\x06 \x03(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\x11\n\tpost_time\x18\x08 \x01(\t\x12\x17\n\x0frelated_tag_arr\x18\t \x03(\t\"2\n\x03Tag\x12\x16\n\x07tagname\x18\x01 \x01(\tB\x05\x8aM\x02\x08\x01\x12\x13\n\x0b\x61rticle_arr\x18\x02 \x03(\tb\x06proto3')


_USER = DESCRIPTOR.message_types_by_name['User']
_ARTICLE = DESCRIPTOR.message_types_by_name['Article']
_TAG = DESCRIPTOR.message_types_by_name['Tag']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
    'DESCRIPTOR': _USER,
    '__module__': 'koke_kokko_pb2'
    # @@protoc_insertion_point(class_scope:csdi.User)
})
_sym_db.RegisterMessage(User)

Article = _reflection.GeneratedProtocolMessageType('Article', (_message.Message,), {
    'DESCRIPTOR': _ARTICLE,
    '__module__': 'koke_kokko_pb2'
    # @@protoc_insertion_point(class_scope:csdi.Article)
})
_sym_db.RegisterMessage(Article)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), {
    'DESCRIPTOR': _TAG,
    '__module__': 'koke_kokko_pb2'
    # @@protoc_insertion_point(class_scope:csdi.Tag)
})
_sym_db.RegisterMessage(Tag)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _USER.fields_by_name['email']._options = None
    _USER.fields_by_name['email']._serialized_options = b'\212M\002\010\001'
    _ARTICLE.fields_by_name['article_id']._options = None
    _ARTICLE.fields_by_name['article_id']._serialized_options = b'\212M\002\010\001'
    _TAG.fields_by_name['tagname']._options = None
    _TAG.fields_by_name['tagname']._serialized_options = b'\212M\002\010\001'
    _USER._serialized_start = 58
    _USER._serialized_end = 230
    _ARTICLE._serialized_start = 233
    _ARTICLE._serialized_end = 422
    _TAG._serialized_start = 424
    _TAG._serialized_end = 474
# @@protoc_insertion_point(module_scope)
